export const arrayOfWords = [
    ["to arise", "arose", "arisen", "erguer, levantar"],
    ["to awake", "awoke", "awoken", "acordar, despertar"],
    ["to be", "was / were", "been", "ser, estar, ficar"],
    ["to bear", "bore", "borne", "suportar, aguentar"],
    ["to beat", "beat", "beaten", "bater, espancar, superar, vibrar, palpitar"],
    ["to become", "became", "become", "tornar-se"],
    ["to begin", "began", "begun", "começar, iniciar"],
    ["to bend", "bent", "bent", "curvar, entortar, franzir, dirigir, desistir"],
    ["to bet", "bet", "bet", "apostar"],
    ["to bid", "bade", "bidden", "oferecer, convidar, ordenar, desejar, leiloar"],
    ["to bind", "bound", "bound", "atar, amarrar, obrigar"],
    ["to bite", "bit", "bitten", "morder, engolir a isca"],
    ["to bleed", "bled", "bled", "sangrar, perder sangue;"],
    ["to blow", "blew", "blown", "soprar, assobiar, fazer soar"],
    ["to break", "broke", "broken", "quebrar, romper, violar"],
    ["to breed", "bred", "bred", "procriar, gerar, fazer criação, educar, ensinar"],
    ["to bring", "brought", "brought", "trazer, servir, causar, executar, induzir"],
    ["to build", "built", "built", "construir, edificar, fabricar"],
    ["to burn", "burnt", "burnt", "queimar, incendiar, carbonizar"],
    ["to burst", "burst", "burst", "arrebentar, explodir, brotar, exclamar"],
    ["to buy", "bought", "bought", "comprar"],
    ["to cast", "cast", "cast", "arremessar, jogar, derrubar, moldar"],
    ["to catch", "caught", "caught", "pegar, capturar, entender, adquirir"],
    ["to choose", "chose", "chosen", "escolher, selecionar, preferir"],
    ["to cling", "clung", "clung", "pegar-se, unir-se, aderir"],
    ["to clothe", "clothed", "clothed", "vestir, cobrir"],
    ["to come", "came", "come", "vir, chegar"],
    ["to cost", "cost", "cost", "custar"],
    ["to creep", "crept", "crept", "engatinhar, arrastar-se no chão, andar de rasto"],
    ["to crow", "crew", "crowed", "cacarejar"],
    ["to cut", "cut", "cut", "cortar, partir, reduzir, recortar, castrar"],
    ["to deal", "dealt", "dealt", "dar, distribuir, repartir, dividir, espalhar, negociar"],
    ["to dig", "dug", "dug", "cavar, escavar"],
    ["to do", "did", "done", "fazer"],
    ["to draw", "drew", "drawn", "desenhar, extrair, sair"],
    ["to drink", "drank", "drunk", "beber"],
    ["to drive", "drove", "driven", "dirigir, guiar"],
    ["to dwell", "dwelt", "dwelt", "residir, ficar por um tempo, enfatizar, insistir em"],
    ["to eat", "ate", "eaten", "comer"],
    ["to fall", "fell", "fallen", "cair, desaguar, abater-se, decrescer, diminuir"],
    ["to feed", "fed", "fed", "alimentar, nutrir"],
    ["to feel", "felt", "felt", "sentir, notar"],
    ["to fight", "fought", "fought", "lutar, brigar"],
    ["to find", "found", "found", "achar, encontrar"],
    ["to flee", "fled", "fled", "fugir, escapar, evitar, correr"],
    ["to fling", "flung", "flung", "lançar, arremessar"],
    ["to fly", "flew", "flown", "voar"],
    ["to forbid", "forbade", "forbidden", "proibir"],
    ["to forget", "forgot", "forgotten", "esquecer(-se)"],
    ["to forgive", "forgave", "forgiven", "perdoar"],
    ["to forsake", "forsook", "forsaken", "abandonar, desertar, largar; abrir mão de"],
    ["to freeze", "froze", "frozen", "congelar, gelar"],
    ["to get", "got", "got", "obter, conseguir"],
    ["to give", "gave", "given", "dar"],
    ["to go", "went", "gone", "ir"],
    ["to grow", "grew", "grown", "crescer, florescer, germinar"],
    ["to hang", "hung", "hung", "pendurar, suspender"],
    ["to have", "had", "had", "ter, possuir"],
    ["to hear", "heard", "heard", "ouvir, escutar, ter notícias"],
    ["to heave", "hove", "hove", "puxar"],
    ["to hew", "hewed", "hewn", "reduzir, talhar"],
    ["to hide", "hid", "hidden", "esconder(-se), ocultar"],
    ["to hit", "hit", "hit", "bater, chocar-se"],
    ["to hold", "held", "held", "segurar, agarrar"],
    ["to hurt", "hurt", "hurt", "ferir(-se), machucar"],
    ["to keep", "kept", "kept", "manter, conservar, preservar"],
    ["to kneel", "knelt", "knelt", "ajoelhar-se"],
    ["to knit", "knit", "knit", "tricotar"],
    ["to know", "knew", "known", "saber, conhecer"],
    ["to lay", "laid", "laid", "pôr, colocar, derrubar, deitar"],
    ["to lead", "led", "led", "conduzir, liderar, dirigir, comandar"],
    ["to leap", "leapt", "leapt", "saltar, pular, transportar, cobrir (os animais)"],
    ["to learn", "learnt", "learnt", "aprender, ficar sabendo"],
    ["to leave", "left", "left", "partir, deixar, sair"],
    ["to lend", "lent", "lent", "emprestar"],
    ["to let", "let", "let", "permitir, deixar"],
    ["to lie", "lay", "lain", "deitar, jazer"],
    ["to light", "lit", "lit", "acender, iluminar"],
    ["to lose", "lost", "lost", "perder"],
    ["to make", "made", "made", "fazer, criar, elaborar"],
    ["to mean", "meant", "meant", "significar, querer dizer"],
    ["to meet", "met", "met", "encontrar(-se), reunir(-se)"],
    ["to partake", "partook", "partaken", "participar"],
    ["to pay", "paid", "paid", "pagar"],
    ["to put", "put", "put", "pôr, colocar"],
    ["to quit", "quit", "quit", "desistir, abandonar"],
    ["to read", "read", "read", "ler, interpretar"],
    ["to ride", "rode", "ridden", "cavalgar, andar de bibicleta ou carro"],
    ["to ring", "rang", "rung", "soar, tocar (campainha, telefone)"],
    ["to rise", "rose", "risen", "erguer-se, levantar-se"],
    ["to run", "ran", "run", "correr, apressar-se"],
    ["to saw", "sawed", "sawn", "serrar"],
    ["to say", "said", "said", "dizer, afirmar, declarar"],
    ["to see", "saw", "seen", "ver, perceber"],
    ["to seek", "sought", "sought", "procurar, pedir, almejar"],
    ["to sell", "sold", "sold", "vender"],
    ["to send", "sent", "sent", "enviar, mandar"],
    ["to set", "set", "set", "pôr, dispor, ajustar"],
    ["to sew", "sewed", "sewn", "costurar, coser"],
    ["to shake", "shook", "shaken", "sacudir, agitar, apertar a mão (em cumprimento)"],
    ["to shed", "shed", "shed", "derramar, vazar"],
    ["to shine", "shone", "shone", "brilhar"],
    ["to shoot", "shot", "shot", "atirar, ferir com tiro"],
    ["to show", "showed", "shown", "mostrar, apresentar"],
    ["to shred", "shred", "shred", "cortar em pedaços, picar, retalhar, rasgar"],
    ["to shrink", "shrank", "shrunk", "contrair, encolher, recuar"],
    ["to shut", "shut", "shut", "fechar, cerrar; tampar"],
    ["to sing", "sang", "sung", "cantar"],
    ["to sink", "sank", "sunk", "afundar"],
    ["to sit", "sat", "sat", "sentar(-se)"],
    ["to slay", "slew", "slain", "matar, assassinar, destruir, arruinar"],
    ["to sleep", "slept", "slept", "dormir"],
    ["to slide", "slid", "slid", "escorregar, deslizar"],
    ["to sling", "slung", "slung", "atirar, arremessar"],
    ["to smell", "smelt", "smelt", "cheirar"],
    ["to smite", "smote", "smitten", "bater, espancar"],
    ["to sow", "sowed", "sown", "semear"],
    ["to speak", "spoke", "spoken", "falar"],
    ["to spell", "spelt", "spelt", "soletrar"],
    ["to spend", "spent", "spent", "gastar (dinheiro), passar (tempo)"],
    ["to spill", "spilt", "spilt", "derramar"],
    ["to spin", "spun", "spun", "girar"],
    ["to spit", "spat", "spit", "cuspir"],
    ["to spoil", "spoilt", "spoilt", "estragar, destruir"],
    ["to spread", "spread", "spread", "espalhar, estender"],
    ["to spring", "sprang", "sprung", "saltar, lançar-se, libertar-se"],
    ["to stand", "stood", "stood", "ficar ou pôr-se de pé"],
    ["to steal", "stole", "stolen", "roubar, furtar"],
    ["to stick", "stuck", "stuck", "cravar, fincar"],
    ["to sting", "stung", "stung", "picar, ferroar"],
    ["to stink", "stank", "stunk", "feder; enojar"],
    ["to strew", "strewed", "strewn", "espalhar, polvilhar, aspergir"],
    ["to stride", "strode", "stridden", "caminhar, cavalgar"],
    ["to strike", "struck", "struck", "bater, golpear"],
    ["to string", "strung", "strung", "amarrar, pendurar, enfiar, esticar"],
    ["to strive", "strove", "striven", "aspirar, tentar, esforçar-se"],
    ["to swear", "swore", "sworn", "jurar"],
    ["to sweat", "sweat", "sweat", "suar"],
    ["to sweep", "swept", "swept", "varrer"],
    ["to swell", "swelled", "swollen", "inchar (-se), crescer, encher (os pneus)"],
    ["to swim", "swam", "swum", "nadar"],
    ["to swing", "swung", "swung", "balançar"],
    ["to take", "took", "taken", "tomar, pegar, levar"],
    ["to teach", "taught", "taught", "ensinar"],
    ["to tear", "tore", "torn", "chorar, lacrimejar; rasgar, rachar"],
    ["to tell", "told", "told", "dizer, contar"],
    ["to think", "thought", "thought", "pensar, achar"],
    ["to thrive", "throve", "thriven", "ter sucesso"],
    ["to throw", "threw", "thrown", "lançar, atirar"],
    ["to thrust", "thrust", "thrust", "empurrar"],
    ["to tread", "trod", "trodden", "pisar, andar, pôr os pés"],
    ["to understand", "understood", "understood", "entender, compreender"],
    ["to wake", "woke", "woken", "acordar"],
    ["to wear", "wore", "worn", "vestir, usar, trajar"],
    ["to weave", "wove", "woven", "tecer, trançar"],
    ["to weep", "wept", "wept", "chorar"],
    ["to wet", "wet", "wet", "molhar, umedecer"],
    ["to win", "won", "won", "ganhar, vencer"],
    ["to wind", "wound", "wound", "girar, enrolar-se"],
    ["to wring", "wrung", "wrung", "torcer"],
].sort(() => 0.5 - Math.random());
